# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-2022'

variables:
  solution: '**/*.sln'
  buildPlatform: 'AnyCPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetAuthenticate@0
  displayName: Autenticar Nuget

- task: NuGetToolInstaller@1
  displayName: Instalar Nuget

- task: NuGetCommand@2
  displayName: Instala Pacotes Nuget
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'

- task: MSBuild@1
  displayName: Builda Projeto Boleto
  inputs:
    solution: '$(Build.SourcesDirectory)/Boleto2.Net/Boleto2.Net.csproj'
    msbuildArchitecture: 'x64'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '$(Build.SourcesDirectory)/Boleto2.Net/Boleto2.Net.nuspec'
    packDestination: '$(build.artifactStagingDirectory)/Boleto2.Net.nupkg'
    versioningScheme: 'off'

- task: PublishBuildArtifacts@1
  displayName: Publica Projeto Boleto
  inputs:
    PathtoPublish: '$(Build.artifactStagingDirectory)/Boleto2.Net.nupkg'
    ArtifactName: 'boleto'
    publishLocation: 'Container'